MeuProjetoDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Inclui as URLs do app 'home' na raiz do site
    path('', include('home.urls')),      
    # Inclui as URLs do app 'results' para a rota 'results_home'
    path('results/', include('results.urls')),      
    # Rota para a administração do site
    path('admin/', admin.site.urls),
]

home/urls.py
from django.urls import path
from home import views as views_home

app_name = 'home'

urlpatterns = [
    path('', views_home.home, name='home'),
]

results/urls.py
from django.urls import path

# Importando as views do app 'results' e renomeando para 'views_results'
from results import views as views_results 
app_name = 'results'


urlpatterns = [
    # Rota para a página de clientes desativados
    path('clientesDesativados/', views_results.clientes_desativados, name='clientesDesativados'), 
    # Rota para a página de clientes ativos
    path('clientesAtivos/', views_results.clientes_ativos, name='clientesAtivos'),      
    # Rota para a página com post especifico com o ID
    path('post/<int:post_id>/', views_results.post, name='post_id'),      
    # Rota para a página com todos os posts
    path('', views_results.home, name='results/home'),      
]

home/models.py
from django.db import models

# Create your models here.

results/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):

    context = {
        'texto_principal': 'block texto_principal',
        'title': 'Pagina Home'
    }

    return render(
        request, 
        'home/index.html',
        context
)

results/views.py
from django.shortcuts import render
from results.post import posts
from typing import Any
from django.http import HttpRequest, HttpResponse, Http404


# Create your views here.
def home(request):
    data = posts()
    context= {
        'title': 'Pagina de RESULTADOS',
        'posts': data
        }
    return render(request, 'results/index.html', context)

def post(request: HttpRequest, post_id:int):
    post_encontrado: dict[str, Any] | None = None
    print(type(post_id))


    data = posts()
    print('PostID:',post_id)

    for i in data:
        if i['id'] == int(post_id):
            post_encontrado = i
            break 

    if post_encontrado is None:
    
        raise Http404 ('Post, não existe')
    
    context= {
        'texto_principal': 'Post ID: ',
        'post_id': post_id,
        'post': post_encontrado
        }
        
    return render(request, 'results/post_id.html', context)

def clientes_ativos(request):
    return render(request, 'results/clientesAtivos.html')

def clientes_desativados(request):
    return render(request, 'results/clientesDesativados.html')

home/templates/home/index.html
{% extends "global/templateBase.html" %}

{% block texto_principal %}
    Texto_principal no App HOME
{% endblock texto_principal %} 

results/templates/results/clientesAtivos.html
{% extends "global/templateBase.html" %}

{% block texto_principal%}
    <h1>Texto Principal em ClIENTES ATIVOS </h1>   
{% endblock texto_principal %} 

results/templates/results/clientesDesativados.html
{% extends "global/templateBase.html" %}

{% block texto_principal%}
    <h1>Texto Principal em ClIENTES DESATIVADOS </h1>   
{% endblock texto_principal %} 

results/templates/results/index.html
{% extends "global/templateBase.html" %}

{% comment %} H1 ESTA AQUI  {% endcomment %}
{% block texto_principal%}
    Texto Principal no RESULTS/Home
{% endblock texto_principal %} 

{% comment %} MENU VEIO AQUI  {% endcomment %}

{% comment %} POST SÃO AQUI  {% endcomment %}
{% block posts %}
    {% for post in posts %}
        {% include "global/partials/post.html" %}
    {% endfor %}
{% endblock posts %} 

results/templates/results/post_id.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{  post.title }} - Dato</title>
    <!-- <link rel="stylesheet" href="{% static "results/css/style.css" %}"> -->
    <link rel="stylesheet" href="{% static "global/css/style.css" %}">
</head> 
{% if texto_principal %}
    <h1 class="texto_principal">
        {% block texto_principal %}
            {{texto_principal}}{{post_id}} | Titulo: {{ post.title}}
        {% endblock texto_principal %}
    </h1>
{% endif %}
<body>
    <!-- incluindo Menu.html -->
    {% include "global/partials/menu.html" %}


    <main class="content">
        <article class="post single-post">
            <header>
                <h1 class="post__title">
                    <a class="post_title" href="{% url 'results:post_id' post.id %}">{{post.title}}</a>
                </h1>
            </header>
            <div class="post__body">
                {{post.body}}      
            </div>
        </article>
        
    </main>


</Body>
</html>